# Generated by Django 5.0.6 on 2024-06-24 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='province',
            new_name='state',
        ),
    ]
